// import { Geist, Geist_Mono } from "next/font/google";
import "@/assets/styles/globals.css";
import AuthProvider from "@/components/AuthProvider.jsx";
import { ToastContainer } from "react-toastify";
import { GlobalProvider } from "@/context/GlobalContext.js";
import { SpeedInsights } from "@vercel/speed-insights/next";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <GlobalProvider>
      <AuthProvider>
        <html lang="en">
          {/* <body className={`${geistSans.variable} ${geistMono.variable}`}>{children}</body> */}
          <body>
            <NavBar />
            <main>{children}</main>
            <Footer />
            <ToastContainer />
            <SpeedInsights />
          </body>
        </html>
      </AuthProvider>
    </GlobalProvider>
  );
}
